services:
  etf-green:
    image: ${DOCKER_USERNAME}/ideundeun-etf:${IMAGE_TAG}
    container_name: etf-green
    ports:
      - "127.0.0.1:8084:8080"
    volumes:
      - /home/ubuntu/app/application.yml:/app/application.yml
    environment:
      SPRING_CONFIG_LOCATION: /app/application.yml
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"